### ISSUE TITLE
how to avoid the collision?

### ISSUE THREAD

**Issue by monacv** [otaheri/GrabNet#5]
(the scale is not correct and I cannot fix it)

for this cell:
```
meshes = torch.load('data/grabnet_data/meshes.pt')

N = len(meshes)

for i in range(N):

    obj = meshes[i][0]
    hand = meshes[i][1]

    hand.set_vertex_colors(vc=[245, 191, 177])

    def_color = np.array([[102, 102, 102, 255]])
    if hasattr(obj.visual, 'vertex_colors') and (obj.visual.vertex_colors == np.repeat(def_color, obj.vertices.shape[0], axis=0)).all():
        obj.set_vertex_colors(vc=name_to_rgb['yellow'])
    
    scene = obj.scene()
    scene.add_geometry(hand)
    a = scene.show()
    display(a)
    time.sleep(10)
    clear_output(wait=True)
```

When I run it for a surfboard that is scaled-down, there is still some collision. How can I avoid this collision since it is not realistic?
![Screenshot from 2021-04-13 20-16-54](https://user-images.githubusercontent.com/76495162/114636636-76ac5e00-9c95-11eb-8b2d-a88dd44c09ca.png)

As you see, the surfboard has no holes itself so not sure how one of the fingers has penetrated into the surfboard.
![Screenshot from 2021-04-13 20-19-04](https://user-images.githubusercontent.com/76495162/114636683-9cd1fe00-9c95-11eb-9de3-5fcb82b12663.png)

**Comment by otaheri** [comment]
The code is trained on objects that can fit in a sphere with a 30cm Diameter, this is why big objects need to be down-scaled (automatically) to get the best results. In order to prevent auto downscaling, you can comment out the following line.
https://github.com/otaheri/GrabNet/blob/0b428a72d9575e196503ec56b4c4f5b4fde65914/grabnet/tests/demo_colab.py#L157

 Regarding the penetration, the code works best for non-flat objects and has some failure cases when the objects are flat (like the surfing board). We will try to solve it in the next projects :). Also, the penetration is not due to holes in the surfing board mesh; it is just a non-realistic visualization.
